### ISSUE TITLE
error checking for updates

### ISSUE THREAD

**Issue by Botspot** [matu6968/arduino-ide-arm64#1]
Is this error normal?
![20240521_15h01m21s_grim](https://github.com/matu6968/arduino-ide-arm64/assets/54716352/3bb5694f-50d6-4be0-bc12-36c22cbdb6e3)
I would assume it is, so the next question is can it be hidden?

**Comment by matu6968** [comment]
This error is normal as it is a unofficial build and the build update channel for ARM64 **does not** currently exist yet.

**Comment by matu6968** [comment]
As for the update error message AFAIK it can't be hidden permanently in the settings from what i could find in the UI. All you can do about it is click the X button to hide the message every time it starts up.
